[project]
name = "escpostest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "html2image>=2.0.7",
    "python-escpos>=3.1",
]
